config/routes.rb
MassSpec::Application.routes.draw do

  get "user_uploads/uploads"

  devise_for :users

  get "general/index"
  
  match '/mass_params/create_file'
  match '/mass_params/new_file'

  match 'mass_params/update_params' => 'mass_params#update_params', :as => :update_params
  match 'mass_params/choose' => 'mass_params#choose', :as => :choose_params
  match '/mass_data/choose' => 'mass_data#choose', :as => :choose_data
  match '/mass_data/update_choice' => 'mass_data#update_choice', :as => :update_choice
  resources :mass_data, :mass_params
  match '/review' => 'results#review', :as => :review
  get '/finish' => 'results#index', :as => :finish_index
  match '/review/upload' => 'general#upload', :as => :upload
  match '/mass_data/upload' => 'mass_data#upload', :as => :upload_data
  match '/mass_params/upload' => 'mass_params#upload', :as => :upload_params
  match '/about' => 'general#about', :as => :about
  match '/downloads' => 'general#downloads', :as => :downloads
  match '/examples' => 'general#examples', :as => :examples
  match '/applications' => 'general#applications', :as => :applications
  match '/examples' => 'general#examples', :as => :examples
  match '/uploads' => 'user_uploads#uploads', :as => :uploads
  match '/instructions' => 'general#instructions', :as => :instructions
  root :to => 'general#index'

  post '/finish' => 'results#finish', :as => :post_finish

  match '/downloads/:file' => 'general#download_file', :as => :download_file, :constraints  => { :file => /[0-z\.]+/ }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/models/mass_param.rb
class MassParam < ActiveRecord::Base
  has_many :results
  belongs_to :user

  attr_accessible :title, :s3id, :user_id

  def get_title
    t = /.*\/(.*)$/.match(s3id)
    return t.captures[0]
  end

  def self.get_record_or_nil(id)
    begin
      return MassParam.find(id)
    rescue ActiveRecord::RecordNotFound
      return nil
    end
  end

end

app/controllers/mass_params_controller.rb
class MassParamsController < ApplicationController
  before_filter :authenticate_user!
	@@fields = ['charge_min', 'charge_max', 'mz_tolerance', 'mz_tolerance_2', 'scan_tolerance', 'pattern_size', 'min_score', 'retention_time_window', 'include_mass_mod', 'sigma', 'per_sigma', 'log_file', 'search_pattern', 'alt_pattern']
  @@selects = ['full_output', 'inclusion_list', 'mz_charge', 'mz_charge_scan']

  def create
    create_model(:MassParam, :mass_params_id)
  end

  def new
    @disabled_params = true
    current_result = current_user.current_result
    current_mass_params = if current_result then current_result.get_mass_params end
    if current_result && current_mass_params
      @message = "You have already uploaded #{current_mass_params.get_title}."
    else
      @message = "Please choose a .txt or .params file to upload."
    end
    @s3_direct_post = S3_BUCKET.presigned_post(key: "#{current_user.id}/params/#{SecureRandom.uuid}/${filename}", success_action_status: 201)
    @mass_param = MassParam.new
  end
  
  def new_file
    patterns_more = params['alt_pattern_more']
    file = params[:file]
    filename = file[:filename] + ".params"
    contents = ""
    contents = contents + get_fields_str(file)
    patterns_more.each_line {|p| contents = contents + "alt_pattern: " + p}
    contents = contents + "\n" unless contents[-1] === "\n"
    contents = contents + get_selects_str(file)
    send_data(contents, :filename => filename, :disposition => "attachment")
  end
  
  def get_fields_str(file)
    fields_str = ""
    @@fields.each do |f| 
      if !file[f].empty?
        fields_str = fields_str + f + ": " + file[f]
        fields_str = fields_str + ".log" if f === 'log_file'
        fields_str = fields_str + "\n"
      end
    end
    fields_str
  end
  
  def get_selects_str(file)
    selects_str = ""
    @@selects.each { |s| selects_str = selects_str + s + ": " + file[s] + "\n" }
    selects_str
  end
  
  def choose
    @all_params = MassParam.where(:user_id => current_user.id)
    @disabled_params = true
    @results = current_user.results
    current_result = current_user.current_result
    current_mass_params = if current_result then current_result.get_mass_params end
    if current_result && current_mass_params
      @message = "You have already uploaded #{current_mass_params.get_title}."
    else
      @message = "Please choose a .txt or .params file to upload."
    end
    @s3_direct_post = S3_BUCKET.presigned_post(key: "params/#{current_user.id}/${filename}", success_action_status: 201)
    @mass_param = MassParam.new
  end

  def update_params
    update_model_choice(params[:data_id], :mass_params_id, :MassParam, "params")
  end
end

app/helpers/mass_params_helper.rb
module MassParamsHelper
end

app/views/mass_params/_form.html.haml
= form_tag mass_params_new_file_path(@file), :method => :put do
  = javascript_include_tag "mass_params"
  %div{:id => 'form', :class => "param_form"}
    = label :file, :filename, 'File Name'
    = text_field :file, 'filename'
    = '.params'
    <br>
    <br>
    <br>
    = label :file, :charge_min, 'charge_min: '
    = text_field :file, 'charge_min'
    <br>
    = label :file, :charge_max, 'charge_max: '
    = text_field :file, 'charge_max'
    <br>
    = label :file, :mz_tolerance, 'mz_tolerance: '
    = text_field :file, 'mz_tolerance'
    <br>
    = label :file, :mz_tolerance_2, 'mz_tolerance_2: '
    = text_field :file, 'mz_tolerance_2'
    <br>
    = label :file, :scan_tolerance, 'scan_tolerance: '
    = text_field :file, 'scan_tolerance'
    <br>
    = label :file, :pattern_size, 'pattern_size: '
    = text_field :file, 'pattern_size'
    <br>
    = label :file, :min_score, 'min_score: '
    = text_field :file, 'min_score'
    <br>
    = label :file, :retention_time_window, 'retention_time_window: '
    = text_field :file, 'retention_time_window'
    <br>
    = label :file, :include_mass_mod, 'include_mass_mod: '
    = text_field :file, 'include_mass_mod'
    <br>
    = label :file, :sigma, 'sigma: '
    = text_field :file, 'sigma'
    <br>
    = label :file, :per_sigma, 'per_sigma: '
    = text_field :file, 'per_sigma'
    <br>
    = label :file, :log_file, 'log_file: '
    = text_field :file, 'log_file'
    = '.log'
    <br>
    = label :file, :search_pattern, 'search_pattern: '
    = text_field :file, 'search_pattern'
    <br>
    = label :file, :alt_pattern, 'alt_pattern: '
    = text_field :file, 'alt_pattern'
    <br>
    = label :file, :alt_pattern_more, 'additional patterns: '
    = text_area_tag :alt_pattern_more, nil, size: "40x10"
    <br>
    = "Examples: alt_pattern: pattern=0.1, 0.5, 0.25; mw=300; prior=0.0001"
    <br><br>
    = label :file, :full_output, 'full_output: '
    = select(:file, 'full_output', { "false" => "false", "true" => "true"})
    <br>
    = label :file, :inclusion_list, 'inclusion_list: '
    = select(:file, 'inclusion_list', { "false" => "false", "true" => "true"})
    <br>
    = label :file, :mz_charge, 'mz_charge: '
    = select(:file, 'mz_charge', { "false" => "false", "true" => "true"})
    <br>
    = label :file, :mz_charge_scan, 'mz_charge_scan: '
    = select(:file, 'mz_charge_scan', { "false" => "false", "true" => "true"})
    <br>
  
  = submit_tag 'Save File', :class => "center-btn btn"

app/views/mass_params/choose.html.haml
-#  This file is app/views/mass_params/choose.html.haml

%h1 Choose Existing Parameters File


%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'tabs'}
      = button_to 'Upload Parameters', new_mass_param_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get
      = button_to 'Choose Existing Files', choose_params_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get, :disabled => @disabled_params

    %div{:id => 'content'}
      %div
        = form_tag update_params_path, :method => :post, :id => "data_form" do
          %p{:class => 'msg'} #{@message}
          %p <br />
          - @all_params.each do |data|
            %div{:id => 'tabs'}
              = radio_button_tag "data_id", data.id
              = data.get_title
          %p <br />
          = submit_tag 'Save and Next', :id => 'data_submit', :class => 'center-btn btn'

app/views/mass_params/create_file.html.haml
-#  This file is app/views/mass_params/create_file.html.haml

%h1 Create New Parameters File (Graph Search)

%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p= @message
      
      %div{:id => 'form', :class => ""}
        = render "mass_params/form"
      = button_to "Back", new_mass_param_path, :class => 'center-btn btn', :method => :get

app/views/mass_params/new.html.haml
-#  This file is app/views/mass_params/new.html.haml

%h1 Upload New Parameters File

%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'tabs'}
      = button_to 'Upload Parameters File', new_mass_param_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get, :disabled => @disabled_params
      = button_to 'Choose Existing Files', choose_params_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get

    %div{:id => 'content'}
      %p= @message
      
      %div{:id => 'form', :class => "directUpload"}
        %div= file_field_tag :param_file, :class => 'form-item', :data => {:url => @s3_direct_post.url.to_s, 
        :formData => @s3_direct_post.fields.to_json.html_safe }
        = form_for(@mass_param, html: { class: "directUpload" }) do |f| 
          = f.submit 'Save and Next',:class => 'center-btn btn'
        = link_to "Create a new parameters file", mass_params_create_file_path

:javascript 
  s3_upload_file('#{@s3_direct_post.url}', #{@s3_direct_post.fields.to_json.html_safe});