config/routes.rb
MassSpec::Application.routes.draw do

  get "user_uploads/uploads"

  devise_for :users

  get "general/index"
  
  match '/mass_params/create_file'
  match '/mass_params/new_file'

  match 'mass_params/update_params' => 'mass_params#update_params', :as => :update_params
  match 'mass_params/choose' => 'mass_params#choose', :as => :choose_params
  match '/mass_data/choose' => 'mass_data#choose', :as => :choose_data
  match '/mass_data/update_choice' => 'mass_data#update_choice', :as => :update_choice
  resources :mass_data, :mass_params
  match '/review' => 'results#review', :as => :review
  get '/finish' => 'results#index', :as => :finish_index
  match '/review/upload' => 'general#upload', :as => :upload
  match '/mass_data/upload' => 'mass_data#upload', :as => :upload_data
  match '/mass_params/upload' => 'mass_params#upload', :as => :upload_params
  match '/about' => 'general#about', :as => :about
  match '/downloads' => 'general#downloads', :as => :downloads
  match '/examples' => 'general#examples', :as => :examples
  match '/applications' => 'general#applications', :as => :applications
  match '/examples' => 'general#examples', :as => :examples
  match '/uploads' => 'user_uploads#uploads', :as => :uploads
  match '/instructions' => 'general#instructions', :as => :instructions
  root :to => 'general#index'

  post '/finish' => 'results#finish', :as => :post_finish

  match '/downloads/:file' => 'general#download_file', :as => :download_file, :constraints  => { :file => /[0-z\.]+/ }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/mass_data_controller.rb
class MassDataController < ApplicationController
  before_filter :authenticate_user!
  def create
    create_model(:MassDatum, :mass_data_id)
  end

  def new
    @disabled_page = true
    current_result = current_user.current_result
    current_mass_data = if current_result then current_result.get_mass_data else nil end
    if current_result && current_mass_data
      @message = "You have already uploaded #{current_mass_data.get_title}."
    else
      @message = "Please choose a .mzxml file to upload."
    end
    @s3_direct_post = S3_BUCKET.presigned_post(key: "#{current_user.id}/data/#{SecureRandom.uuid}/${filename}", success_action_status: 201)
    @mass_datum = MassDatum.new
  end

  def choose
    @all_data = MassDatum.where(:user_id => current_user.id)
    @disabled_page = true
    @results = current_user.results
    current_result = current_user.current_result
    current_mass_data = if current_result then current_result.get_mass_data else nil end
    if current_result && current_mass_data
      @message = "You have already uploaded #{current_mass_data.get_title}."
    else
      @message = "Please choose a file to upload."
    end
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: 201)
    @mass_datum = MassDatum.new
  end

  def update_choice
    update_model_choice(params[:data_id], :mass_data_id, :MassDatum, ".mzxml")
  end
end

app/helpers/mass_data_helper.rb
module MassDataHelper
end

app/views/mass_data/choose.html.haml
-#  This file is app/views/mass_data/choose.html.haml

%h1 Choose Existing Data File


%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'tabs'}
      = button_to 'Upload Data', new_mass_datum_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get
      = button_to 'Choose Existing Files', choose_data_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get, :disabled => @disabled_page

    %div{:id => 'content'}
      %div
        = form_tag update_choice_path, :method => :post, :id => "data_form" do
          %p{:class => 'msg'} #{@message}
          %p <br />
          - @all_data.each do |data|
            %div{:id => 'tabs'}
              = radio_button_tag "data_id", data.id
              = data.get_title
          %p <br />
          = submit_tag 'Save and Next', :id => 'data_submit', :class => 'center-btn btn'

app/views/mass_data/new.html.haml
-#  This file is app/views/mass_data/new.html.haml

%h1 Upload New Data File

%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'tabs'}
      = button_to 'Upload Data', new_mass_datum_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get, :disabled => @disabled_page
      = button_to 'Choose Existing Files', choose_data_path, :class => 'center-btn btn tab', :form => {:class => 'tab_buttons'}, :method => :get

    %div{:id => 'content'}
      %p{:class => 'msg'} #{@message}
      
      %div{:class => 'directUpload'}
        %div= file_field_tag :xml_file, :class => 'form-item', :data => {:url => @s3_direct_post.url.to_s,
        :formData => @s3_direct_post.fields.to_json.html_safe }
        = form_for(@mass_datum, html: { class: "directUpload" }) do |f| 
          = f.submit 'Save and Next',:class => 'center-btn btn'

:javascript 
  s3_upload_file('#{@s3_direct_post.url}', #{@s3_direct_post.fields.to_json.html_safe});