config/routes.rb
MassSpec::Application.routes.draw do

  get "user_uploads/uploads"

  devise_for :users

  get "general/index"
  
  match '/mass_params/create_file'
  match '/mass_params/new_file'

  match 'mass_params/update_params' => 'mass_params#update_params', :as => :update_params
  match 'mass_params/choose' => 'mass_params#choose', :as => :choose_params
  match '/mass_data/choose' => 'mass_data#choose', :as => :choose_data
  match '/mass_data/update_choice' => 'mass_data#update_choice', :as => :update_choice
  resources :mass_data, :mass_params
  match '/review' => 'results#review', :as => :review
  get '/finish' => 'results#index', :as => :finish_index
  match '/review/upload' => 'general#upload', :as => :upload
  match '/mass_data/upload' => 'mass_data#upload', :as => :upload_data
  match '/mass_params/upload' => 'mass_params#upload', :as => :upload_params
  match '/about' => 'general#about', :as => :about
  match '/downloads' => 'general#downloads', :as => :downloads
  match '/examples' => 'general#examples', :as => :examples
  match '/applications' => 'general#applications', :as => :applications
  match '/examples' => 'general#examples', :as => :examples
  match '/uploads' => 'user_uploads#uploads', :as => :uploads
  match '/instructions' => 'general#instructions', :as => :instructions
  root :to => 'general#index'

  post '/finish' => 'results#finish', :as => :post_finish

  match '/downloads/:file' => 'general#download_file', :as => :download_file, :constraints  => { :file => /[0-z\.]+/ }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/controllers/general_controller.rb
require 'net/ssh'

class GeneralController < ApplicationController
  before_filter :authenticate_user!, only: [:downloads, :examples]
  
  @@file_downloads = ["CWT_PD.exe", 
                      "Graph_search.exe",
                      "ExampleParams.params",
                      "Tag_finder.exe",
                      "ExampleParams.txt"]

  @@downloads_path = File.join(Rails.root, "public", "downloads_page")

  def index
  end

  def review
  end

  def upload
  end

  def download_file
    @file = params[:file]
    if @@file_downloads.include? @file
      send_file(File.join(@@downloads_path, @file), 
        :disposition => 'attachment',
        :filename => @file, 
        type: 'application/octet-stream')
    else
      flash[:warning] = "Invalid filename"
      redirect_to downloads_path
    end
  end

  def downloads
  end

  def examples
  end

  def about
  end

  def instructions
  end

end

app/helpers/general_helper.rb
module GeneralHelper
end

app/views/general/_sidebar.html.haml
-# sidebar.html.haml using partial

%div{:class => 'card', :id => 'sidebar'}
  %div 
  = button_to 'Instructions', instructions_path, :class => 'btn', :method => :get
  %div
  = button_to 'Upload Data', new_mass_datum_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Choose Parameters', new_mass_param_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Review & Run', review_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Finish', finish_index_path, :class => 'btn', :method => :get

app/views/general/about.html.haml
-#  This file is app/views/general/about.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 About

%div{:id => 'center-parent'}

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p Isotopic signature transfer and mass pattern prediction (IsoStamp) is a computational algorithm for the targeted detection and identification of modified species by mass spectrometry (MS). The IsoStamp algorithm uses predictive pattern matching to produce peak lists of isotopically recoded species.  The peak lists are used for the immediate validation of modified species by full scan MS and to guide subsequent inclusion list-driven tandem MS.
     
      %p <br /> 

      =image_tag asset_path("aboutimg.png")

      %p <br /> We provide two IsoStamp algorithms with further description and references below.

      %p <br /> (1) Graph_Search v1.9:  mzXML files in profile mode are processed using a continuous wavelet transform for peak optimization.  A graph theoretic algorithm is then applied to predict the presence of patterned species. Graph_Search scores based on the clustered peak shape as compared to a theoretical curve, peak abundance, and charge states.

      %p <br /> For references see:

      %p Palaniappan, K. K.; Pitcher, A. A.; Smart, B. P.; Spiciarich, D. R.; Iavarone, A. T.; Bertozzi, C. R.  “Isotopic signature transfer and mass pattern prediction (IsoStamp): An enabling technique for chemically-directed proteomics.”  ACS Chem. Biol. 2011, 6, 829–836.

      %p Austin Pitcher Thesis (LINK).

      %p <br /> (2) Tag_Finder: mzXML files in centroided mode are processed by comparing grouped spectra to the predicted pattern as a function of mass and charge.  Tag_Finder scores on the difference between the predicted and observed peak distribution for tagged vs. untagged species.

      %p <br /> For references see:  manuscript in preparation

      %p <br /> (3) MS2_Filter: Uses the Tag_Finder pattern matching algorithm and the presence of signature fragment peaks to select tandem MS spectra derived from tagged species.  The filtered output file is then used for targeted database searching.

      %p <br /> For references see:  manuscript in preparation

app/views/general/applications.html.haml
-#  This file is app/views/general/applications.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Applications

%div{:id => 'center-parent'}

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p <b>Isotope Targeted Glycoproteomics (IsoTaG)</b>
      %p <br />

      =image_tag asset_path("applicationsimage.png")

      %p Abstract:  Protein glycosylation is a heterogeneous post-translational modification (PTM) that plays an essential role in biological regulation.  However, the diversity found in glycoproteins has undermined efforts to describe the intact glycoproteome via mass spectrometry (MS).  We present IsoTaG, a mass-independent chemical glycoproteomics platform for characterization of intact, metabolically labeled glycopeptides at the whole-proteome scale.  In IsoTaG, metabolic labeling of the glycoproteome is combined with (i) chemical enrichment and isotopic recoding of glycopeptides to select peptides for targeted glycoproteomics using directed MS and (ii) mass-independent assignment of intact glycopeptides.  We structurally assigned 32 N-glycopeptides and over 500 intact and fully elaborated O-glycopeptides from 250 proteins across three human cancer cell lines and also discovered unexpected peptide sequence polymorphisms (pSPs).  The IsoTaG platform is broadly applicable to the discovery of PTMs that are amenable to chemical labeling, as well as novel protein isoforms including pSPs.

      %p <br /> Reference:  Woo, C. M.; Iavarone, A. T.; Spiciarich, D. R.; Palaniappan, K. K.; Bertozzi, C. R. “Isotope-targeted glycoproteomics (IsoTaG): a mass-independent platform for intact N- and O-glycopeptide discovery and analysis” Nat. Methods, 12, 561 (2015).

      %p <br /> <b>Mapping Yeast N-Glycosites with Isotopically Recoded Glycans</b>

      %p <br /> Asparagine-linked glycosylation is a common post-translational modification of proteins; in addition to participating in key macromolecular interactions, N-glycans contribute to protein folding, trafficking, and stability.  Despite their importance, few N-glycosites have been experimentally mapped in the Saccharomyces cerevisiae proteome.  Factors including glycan heterogeneity, low abundance, and low occupancy can complicate site mapping.  Here, we report a novel mass spectrometry-based strategy for detection of N-glycosites in the yeast proteome.  Our method imparts N-glycopeptide mass envelopes with a pattern that is computationally distinguishable from background ions.  Isotopic recoding is achieved via metabolic incorporation of a defined mixture of N-acetylglucosamine isotopologs into N-glycans.  Peptides bearing the recoded envelopes are specifically targeted for fragmentation, facilitating high confidence site mapping.   This strategy requires no chemical modification of the N-glycans or stringent sample enrichment.  Further, enzymatically simplified N-glycans are preserved on peptides.  Using this approach, we identify 133 N-glycosites spanning 58 proteins, nearly doubling the number of experimentally observed N-glycosites in the yeast proteome.

      %p <br />Reference: Breidenbach, M. A., Palaniappan, K. K., Pitcher, A. A. & Bertozzi, C. R. Mapping yeast N-glycosites with isotopically recorded glycans. Mol. Cell Proteomics 11, M111.015339 (2012).

      %p <br /> Do you have an application and would you like it highlighted here?  Email us!

app/views/general/citations.html.haml
-#  This file is app/views/general/citations.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Citations

%div{:id => 'center-parent'}

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p 1.  Eget consequat rhoncus ultricies neque ut eu. Pede nec rutrum morbi quisque felis erat, rhoncus vitae wisi nibh fusce mi, in massa id lobortis nulla ipsum. Nullam odio magna, in illo mauris aliquam rutrum. Semper ornare felis, pede gravida consectetuer, lacus est vehicula pede. Dolor lorem quis, donec dui orci, egestas tempus congue, pretium facilisi mauris ipsum aliquam. Praesent vestibulum dignissim ligula donec maecenas urna. Enim lectus risus nunc, elementum diam sed, fusce ac libero leo in in justo, lectus justo tempor viverra aliquam. Gravida ullamcorper bibendum at facilisis vivamus minus, proin donec erat suscipit, ut mauris cum vel, venenatis donec odio fusce lectus egestas, mauris eu lorem lectus. Nisl posuere tincidunt vitae, tellus leo in fermentum lectus tempus.

      %p 2.  Eget consequat rhoncus ultricies neque ut eu. Pede nec rutrum morbi quisque felis erat, rhoncus vitae wisi nibh fusce mi, in massa id lobortis nulla ipsum. Nullam odio magna, in illo mauris aliquam rutrum. Semper ornare felis, pede gravida consectetuer, lacus est vehicula pede. Dolor lorem quis, donec dui orci, egestas tempus congue, pretium facilisi mauris ipsum aliquam. Praesent vestibulum dignissim ligula donec maecenas urna. Enim lectus risus nunc, elementum diam sed, fusce ac libero leo in in justo, lectus justo tempor viverra aliquam. Gravida ullamcorper bibendum at facilisis vivamus minus, proin donec erat suscipit, ut mauris cum vel, venenatis donec odio fusce lectus egestas, mauris eu lorem lectus. Nisl posuere tincidunt vitae, tellus leo in fermentum lectus tempus.

      %p 3.  Eget consequat rhoncus ultricies neque ut eu. Pede nec rutrum morbi quisque felis erat, rhoncus vitae wisi nibh fusce mi, in massa id lobortis nulla ipsum. Nullam odio magna, in illo mauris aliquam rutrum. Semper ornare felis, pede gravida consectetuer, lacus est vehicula pede. Dolor lorem quis, donec dui orci, egestas tempus congue, pretium facilisi mauris ipsum aliquam. Praesent vestibulum dignissim ligula donec maecenas urna. Enim lectus risus nunc, elementum diam sed, fusce ac libero leo in in justo, lectus justo tempor viverra aliquam. Gravida ullamcorper bibendum at facilisis vivamus minus, proin donec erat suscipit, ut mauris cum vel, venenatis donec odio fusce lectus egestas, mauris eu lorem lectus. Nisl posuere tincidunt vitae, tellus leo in fermentum lectus tempus.

app/views/general/downloads.html.haml
-#  This file is app/views/general/examples.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Downloads

%div{:id => 'center-parent'}

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p <b> Conversion of RAW files to mzXML files: </b>

      %p <br> Please use: <a href="http://tools.proteomecenter.org/wiki/index.php?title=Software:ReAdW">ReAdW.exe</a>

      %p  <br> User notes:
      %p{:class => 'indent'} – Must install on a computer with Thermo’s XCalibur software installed
      %p{:class => 'indent'} - MSConvert in 32-bit and peakpicking on will also work for conversion
      %p{:class => 'indent'} – We do not guarantee program function with mzXML converters other than ReAdW.  If your mzXML file is not being processed properly, please get in touch with us, and we’re happy to troubleshoot.

      %p <br> <b> Standalone Windows Executables: </b>

      %p{:class => 'indent'} <br> <a href="/downloads/CWT_PD.exe">CWT_PD.exe</a>
      %p{:class => 'indent'} <a href="/downloads/Graph_search.exe">Graph_search.exe</a>
      %p{:class => 'indent'} <a href="/downloads/ExampleParams.params">ExampleParams.params</a>
      %p{:class => 'indent'} <br> – CWT_PD and Graph_search are only compatible with Orbitrap XL data files
      %p{:class => 'indent'} – CWT_PD accepts file inputs in profile mode only
      %p{:class => 'indent'} – Graph_search accepts file inputs from CWT_PD only

      %p <br>
      %p{:class => 'indent'} <a href="/downloads/Tag_finder.exe">Tag_finder.exe</a>
      %p{:class => 'indent'} <a href="/downloads/ExampleParams.txt">ExampleParams.txt</a> 
      %p <br>

      %p{:class => 'indent'} – Tag_finder is compatible with any Thermo Orbitrap data files.
      %p{:class => 'indent'} – Tag_finder accepts file inputs in centroided mode only.

      %p <br> <b> Detailed Instructions for Use: </b>

      %p <br> GRAPH_SEARCH: 

      %p{:class => 'indent'} <br> 1.	Convert RAW file to mzXML in profile mode using ReAdW.
      %p{:class => 'indent2'}a.	 Open a Windows command line (Start -> type cmd in search bar)
      %p{:class => 'indent2'}b.	Navigate to the folder containing ReAdW.exe
      %p{:class => 'indent2'}c.	Run ReAdW conversion by typing:
      %p{:class => 'indent3'}ReAdW.exe --mzXML yourfile.RAW

      %p{:class => 'indent'} <br> 2.	Convert mzXML to processed mzXML with CWT_PD
      %p{:class => 'indent2'}a.	In Windows command line navigate to the folder containing CWT_PD.exe
      %p{:class => 'indent2'}b.	Run CWT_PD by typing:
      %p{:class => 'indent3'}CWT_PD –i yourfile.mzXML –o yourfile_processed.mzXML

      %p{:class => 'indent2'} <br> A list of scans as they are being processed will be output on the screen, and a processed mzXML file should be produced at the end.

      %p{:class => 'indent'} <br> 3.	Run graph_search to find patterned species in your file
      %p{:class => 'indent2'}a.	In Windows command line navigate to the folder containing graph_search.exe
      %p{:class => 'indent2'}b.	Params text file: this is where you can specify what pattern to search for, scoring, etc.
      %p{:class => 'indent2'}c.	Run graph_search by typing:
      %p{:class => 'indent3'}graph_search –i yourfile_processed.mzXML –p paramsfile.txt

      %p{:class => 'indent2'} <br> Graph search will search your data for patterned species and output different files detailing the hits.


      %p <br> TAG_FINDER: 

      %p{:class => 'indent'} <br> 1.	Convert your file to a centroided mzXML file directly using a conversion software such as ReAdW type: 
      %p{:class => 'indent2'}ReAdW.exe --mzXML –c yourfile.RAW

      %p{:class => 'indent'} <br> 2.	Run tag_finder to find patterned species in your file
      %p{:class => 'indent2'}a.	In Windows command line navigate to the folder containing tag_finder.exe
      %p{:class => 'indent2'}b.	Tag_finder is defaulted to the dibromide pattern on peptides.  To run tag_finder type: 
      %p{:class => 'indent3'}tag_finder.exe yourfile.mzXML
      %p{:class => 'indent2'}c.	To run tag_finder with your preferred settings type:
      %p{:class => 'indent3'}tag_finder.exe yourfile.mzXML yoursettings.txt

      %p{:class => 'indent2'} <br> Tag_finder will search your data for patterned species and output a chart and an inclusion list.  If you file has tandem MS spectra, tag_finder will automatically detect this, and then generate a filtered.mzXML file containing only tandem MS spectra derived from patterned species.

app/views/general/examples.html.haml
-#  This file is app/views/general/examples.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Examples

%div{:id => 'center-parent'}

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p We provide four example datasets using our workflow.  These files were collected at QB3 Mass Spectrometry Facility at the University of California, Berkeley, using an Orbitrap XL.

      %p <br> <b> Example 1.  </b> <br> A model dataset.  A single O-GlcNAcylated protein (alpha crystallin, P02489) was chemoenzymatically labeled and tagged with a dibrominated tag (Figure 1).  The entire protein was digested and analyzed by full scan MS.

      %p <br> <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB33298.RAW">ORB33298.RAW</a>
      %p <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB33298_centroid.mzXML">ORB33298_centroid.mzXML</a>

      %p <br> <b> Example 2. </b> <br> A model dataset.  A single O-GlcNAcylated protein (alpha crystallin, P02489) was chemoenzymatically labeled and tagged with a dibrominated tag (Figure 1).  The entire protein was digested and analyzed by tandem MS2. <br>

      %p <br> <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB33545.RAW">ORB33545.RAW</a>
      %p <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB33545_centroid.mzXML">ORB33545_centroid.mzXML</a>

      %p <br>

      = image_tag asset_path("examples1.png")
      <br> <b> Figure 1. </b> Structure of the glycopeptide before and after isotopic recoding in Example 1 and Example 2.

      %p <br> <b> Example 3. </b> <br> A complex dataset.  GalNAz-labeled Jurkat cells were tagged with a cleavable biotin probe, enriched, and digested with trypsin (Figure 2).  The probe was cleaved to yield a highly enriched pool of isotopically recoded glycopeptides.  The isotopically recoded glycopeptides were analyzed by full scan MS.

      %p <br> <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB36015.RAW">ORB36015.RAW</a>
      %p <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB36015_centroid.mzXML">ORB36015_centroid.mzXML</a>
      
      %p <br> <b> Example 4. </b> <br> A complex dataset.  GalNAz-labeled Jurkat cells were tagged with a cleavable biotin probe, enriched, and digested with trypsin.  The probe was cleaved to yield a highly enriched pool of isotopically recoded glycopeptides.  The isotopically recoded glycopeptides were analyzed by full scan MS, and then using an inclusion list, tandem MS2/MS3 spectra were collected. <br>

      %p <br> <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB36728.RAW">ORB36728.RAW</a>
      %p <a href="https://s3-us-west-2.amazonaws.com/massspec/examples/ORB36728_centroid.mzXML">ORB36728_centroid.mzXML</a> 

      %p <br>

      = image_tag asset_path("examples2.png")
      <br> <b> Figure 2. </b> Workflow for sample preparation to obtain datasets in Example 3 and Example 4.

app/views/general/index.html.haml
-#  This file is app/views/general/index.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Isotopic Signature Transfer and Mass Pattern Prediction (IsoStamp) for Targeted Mass Spectrometry

%div{:id => 'center-parent'}
  = render "sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p Developed by the Bertozzi Group, 2015.

      %p <br />

      %p Isotopic signature transfer and mass pattern prediction (IsoStamp) is a computational algorithm for the targeted detection and identification of modified species by mass spectrometry (MS). The IsoStamp algorithm uses predictive pattern matching to produce peak lists of isotopically recoded species.  The peak lists are used for the immediate validation of modified species by full scan MS and to guide subsequent inclusion list-driven tandem MS.
     
      %p <br /> 

      =image_tag asset_path("aboutimg.png")

      %p <br /> We provide two IsoStamp algorithms with further description and references below.

      %p <br /> <b>(1) Graph_Search v1.9:</b>  mzXML files in profile mode are processed using a continuous wavelet transform for peak optimization.  A graph theoretic algorithm is then applied to predict the presence of patterned species. Graph_Search scores based on the clustered peak shape as compared to a theoretical curve, peak abundance, and charge states.

      %p <br /> For references see:

      %p Palaniappan, K. K.; Pitcher, A. A.; Smart, B. P.; Spiciarich, D. R.; Iavarone, A. T.; Bertozzi, C. R.  “Isotopic signature transfer and mass pattern prediction (IsoStamp): An enabling technique for chemically-directed proteomics.”  ACS Chem. Biol. 2011, 6, 829–836.   <a href="/index/cb100338x.pdf">PDF</a>

      %p <br /> Austin Pitcher Thesis  <a href="/index/AustinPitcherThesis.pdf">PDF</a>

      %p <br /> <b>(2) Tag_Finder:</b> mzXML files in centroided mode are processed by comparing grouped spectra to the predicted pattern as a function of mass and charge.  Tag_Finder scores on the difference between the predicted and observed peak distribution for tagged vs. untagged species.

      %p <br /> MS2_Filter (a component of Tag_Finder): Uses the Tag_Finder pattern matching algorithm and the presence of signature fragment peaks to select tandem MS spectra derived from tagged species.  The filtered output file is then used for targeted database searching.

      %p <br /> For references see:  <i>manuscript in preparation</i>

    %div
    = button_to 'Instructions', instructions_path, :class => 'center-btn btn', :method => :get

app/views/general/instructions.html.haml
-#  This file is app/views/general/instructions.html.haml
-#  To disable buttons, :disabled => 'true'

%h1 Instructions

%div{:id => 'center-parent'}
  = render "general/sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}

      %p <br /> <b>All software is compatible with data from a Thermo Orbitrap mass spectrometer.  It has not been tested with data from other sources.</b>

      %p <br /> <b>TAG_FINDER:</b> Download the params file from the Download page.

      %p <br /> Convert your file to a centroided mzXML file directly using a conversion software such as ReAdW (type: ReAdW.exe --mzXML –c yourfile.RAW) or MSConvert (32 bit, peakPicking true)

      %p <br /> <b>Source for ReAdW:</b> <a href="http://tools.proteomecenter.org/wiki/index.php?title=Software:ReAdW">http://tools.proteomecenter.org/wiki/index.php?title=Software:ReAdW</a>

      %p <br /> Upload mzXML file and params file to start tag_finder.  Tag_finder will generate a chart ordered by match score and an include list .csv for directed tandem MS.  You will receive an email when the search completes with a link to your results.

      %p <br /> <b>MS2_Filter:</b>

      %p <br /> Tag_Finder will automatically detect if the dataset contains tandem MS data.  If so, it will filter the dataset for spectra deriving from (1) patterned species in the MS1 and/or (2) expected glycopeptide fragments.

      %p <br /> <br /> <br /> <b>INSTRUCTIONS FOR DOWNLOADED EXECUTABLES:</b>

      %p <br /> <b>TAG_FINDER:</b> Download the params file from the Downloads page

      %p 1.	Convert your file to a centroided mzXML file directly using a conversion software such as ReAdW (type: ReAdW.exe --mzXML –c yourfile.RAW)

      %p  <br /> 2.	Run tag_finder to find patterned species in your file
      %p{:class => 'indent'} a.	In Windows command line navigate to the folder containing tag_finder.exe
      %p{:class => 'indent'} b.	Tag_finder is defaulted to the dibromide pattern on peptides.  To run tag_finder type: 
      %p{:class => 'indent2'} tag_finder.exe yourfile.mzXML
      %p{:class => 'indent'} c.	To output default settings type:
      %p{:class => 'indent2'} tag_finder.exe –g yoursettings.txt
      %p{:class => 'indent2'} <br /> i.	Settings can be edited to change the base pattern (from peptide to other molecule types) and tag pattern (from dibromide to other pattern types)
      %p{:class => 'indent2'} ii.	Settings can be edited for output types and scoring preferences
      %p{:class => 'indent'} <br /> d.	To run tag_finder with your preferred settings type:
      %p{:class => 'indent2'} tag_finder.exe yourfile.mzXML yoursettings.txt

      %p <br /> <b>MS2_Filter:</b> 
      %p <br /> MS2_filter is a component of Tag_Finder, and will filter for tandem MS spectra that are from tagged species.  MS2_filter will run automatically if Tag_Finder detects tandem MS data in the dataset.
      %p{:class => 'indent'} <br /> i.	Settings can be edited to change the base pattern (from peptide to other molecule types) and tag pattern (from dibromide to other pattern types)
      %p{:class => 'indent'} <br /> ii. Settings can be edited to guide for expected fragments (e.g., glycans) with “###” for signature fragments and “–###” for identification of the neutral or charged loss fragments


      %p <br /> <b>GRAPH_SEARCH:</b> Download the params file from the Downloads page

      %p 1.	Convert RAW file to mzXML in profile mode using ReAdW.
      
      %p{:class => 'indent'} a.	Open a Windows command line (Start -> type cmd in search bar)
      %p{:class => 'indent'} b.	Navigate to the folder containing ReAdW.exe
      %p{:class => 'indent'} c.	Run ReAdW conversion by typing:
      %p{:class => 'indent2'} ReAdW.exe --mzXML yourfile.RAW

      %p <br /> 2.	Convert mzXML to processed mzXML with CWT_PD (this optimizes peak shape in preparation for the pattern recognition program)
      %p{:class => 'indent'} a.	In Windows command line navigate to the folder containing CWT_PD.exe
      %p{:class => 'indent'} b.	Run CWT_PD by typing:
      %p{:class => 'indent2'} CWT_PD –i yourfile.mzXML –o yourfile_processed.mzXML

      %p <br /> A list of scans as they are being processed will be output on the screen, and a processed mzXML file should be produced at the end.

      %p <br /> 3.	Run graph_search to find patterned species in your file
      %p{:class => 'indent'} a.	In Windows command line navigate to the folder containing graph_search.exe
      %p{:class => 'indent'} b.	Params text file: this is where you can specify what pattern to search for, scoring, etc.
      %p{:class => 'indent'} c.	Run graph_search by typing:
      %p{:class => 'indent2'} graph_search –i yourfile_processed.mzXML –p paramsfile.txt

      %p <br /> Graph search will search your data for patterned species and output different files detailing the hits.


      = button_to 'Upload Data', new_mass_datum_path, :class => 'center-btn btn', :method => :get

app/views/general/review.html.haml
-#  This file is app/views/general/review.html.haml

%h1 Review and Run

%div{:id => 'center-parent'}
  = render "sidebar"

  %div{:class => 'card', :id => 'center'}
    %div{:id => 'content'}
      %p This is text for the Review And Run page
      = button_to 'Run', post_finish_path, :class => 'center-btn btn', :method => :post