config/routes.rb
MassSpec::Application.routes.draw do

  get "user_uploads/uploads"

  devise_for :users

  get "general/index"
  
  match '/mass_params/create_file'
  match '/mass_params/new_file'

  match 'mass_params/update_params' => 'mass_params#update_params', :as => :update_params
  match 'mass_params/choose' => 'mass_params#choose', :as => :choose_params
  match '/mass_data/choose' => 'mass_data#choose', :as => :choose_data
  match '/mass_data/update_choice' => 'mass_data#update_choice', :as => :update_choice
  resources :mass_data, :mass_params
  match '/review' => 'results#review', :as => :review
  get '/finish' => 'results#index', :as => :finish_index
  match '/review/upload' => 'general#upload', :as => :upload
  match '/mass_data/upload' => 'mass_data#upload', :as => :upload_data
  match '/mass_params/upload' => 'mass_params#upload', :as => :upload_params
  match '/about' => 'general#about', :as => :about
  match '/downloads' => 'general#downloads', :as => :downloads
  match '/examples' => 'general#examples', :as => :examples
  match '/applications' => 'general#applications', :as => :applications
  match '/examples' => 'general#examples', :as => :examples
  match '/uploads' => 'user_uploads#uploads', :as => :uploads
  match '/instructions' => 'general#instructions', :as => :instructions
  root :to => 'general#index'

  post '/finish' => 'results#finish', :as => :post_finish

  match '/downloads/:file' => 'general#download_file', :as => :download_file, :constraints  => { :file => /[0-z\.]+/ }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Mass Spectrometry
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    %div{:class => "card", :id=>"header"} 
      = link_to (image_tag asset_path("icon.png"), :size => '75x75'), root_path
      %div{:id => "headerLinks"}
        = link_to 'Home', root_path
        |
        = link_to ' Applications', applications_path
        |
        = link_to ' Downloads', downloads_path
        |
        = link_to ' Examples', examples_path
        - if user_signed_in?
          |
          = link_to " Uploads", uploads_path
        %br
        - if user_signed_in?
          = "Logged in as #{current_user.email}"
          |
          = link_to " Edit Profile", edit_user_registration_path
          |
          = link_to " Logout", destroy_user_session_path, :method => :delete
        - else
          = link_to "Signup", new_user_registration_path
          |
          = link_to " Login", new_user_session_path

  %body
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]
      - elsif flash[:alert]
        #alert.message= flash[:alert]

      = yield
  %footer#footer
    &copy2015 UC Berkeley <br>Contact Christina Woo cmwoo@berkeley.edu or David Spiciarich dspiciarich@berkeley.edu for more information.

app/views/layouts/sidebar.html.haml
-# sidebar.html.haml as a partial
-# TODO: add code to decide whether disabled or not for each page
-# TODO: change paths to the already created Data/Param model as opposed to new
- # THIS IS NOT THE ACTUAL SIDEBAR FILE, GO TO THE ONE IN GENERAL/_SIDEBAR

%div{:class => 'card', :id => 'sidebar'}
  %div 
  = button_to 'Instructions', instructions_path, :class => 'btn', :method => :get
  %div
  = button_to 'Data (XML)', new_mass_datum_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Parameters (TXT)', new_mass_param_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Review & Run', review_path, :class => 'btn', :method => :get
  %div 
  = button_to 'Finish', finish_index_path, :class => 'btn', :method => :get